# Generated by Django 5.1.5 on 2025-01-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
    ]
