# Generated by Django 5.1.5 on 2025-02-05 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_Laws',
            fields=[
                ('Law_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Law_Title', models.CharField(max_length=60)),
                ('Law_Category', models.CharField(max_length=25)),
                ('Law_Section', models.CharField(max_length=20)),
                ('Law_Punishment', models.CharField(max_length=50)),
                ('Law_Description', models.TextField()),
                ('Law_link', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Basic Laws',
            },
        ),
        migrations.CreateModel(
            name='Lawyer_Register',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.CharField(max_length=20)),
                ('Experience', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Firm', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=25)),
                ('Image', models.ImageField(upload_to='')),
                ('Price', models.IntegerField()),
            ],
            options={
                'db_table': 'Lawyer_Register',
            },
        ),
        migrations.AlterField(
            model_name='register',
            name='Password',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Book_Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Number', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Lawyer_Name', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=25)),
                ('Appointment_Date', models.DateField()),
                ('Appointment_Time', models.CharField(max_length=25)),
                ('Contact_Time', models.CharField(max_length=25)),
                ('Price', models.IntegerField()),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.register')),
            ],
            options={
                'db_table': 'Book Lawyer',
            },
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('Case_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Number', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.register')),
            ],
            options={
                'db_table': 'User_Details',
            },
        ),
        migrations.CreateModel(
            name='Case_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_Type', models.CharField(max_length=100)),
                ('Complaint_Area', models.CharField(max_length=100)),
                ('Complaint_Date', models.DateField()),
                ('Complaint_Details', models.TextField()),
                ('Complaint_Image', models.ImageField(upload_to='')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.register')),
                ('Case_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user_details')),
            ],
            options={
                'db_table': 'Case_Details',
            },
        ),
    ]
