# Generated by Django 5.1.5 on 2025-02-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_basic_laws_lawyer_register_alter_register_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer_register',
            name='Experience',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
