# Generated by Django 5.1.5 on 2025-02-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_lawyer_register_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_lawyer',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Lawyer_Categories', to='App.lawyer_register'),
        ),
        migrations.AlterField(
            model_name='book_lawyer',
            name='Lawyer_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Lawyer_Name', to='App.lawyer_register'),
        ),
        migrations.AlterField(
            model_name='lawyer_register',
            name='Firm',
            field=models.CharField(max_length=255),
        ),
    ]
