# Generated by Django 5.1.5 on 2025-02-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_book_lawyer_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_laws',
            name='Law_Punishment',
            field=models.CharField(max_length=200),
        ),
    ]
