# Generated by Django 5.1.5 on 2025-02-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_basic_laws_law_punishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_laws',
            name='Law_Section',
            field=models.CharField(max_length=255),
        ),
    ]
