# Generated by Django 5.1.5 on 2025-02-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_basic_laws_law_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic_laws',
            old_name='Law_Section',
            new_name='Law_Relevant',
        ),
    ]
