# Generated by Django 5.1.5 on 2025-02-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_law_section_basic_laws_law_relevant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_laws',
            name='Law_link',
            field=models.URLField(),
        ),
    ]
