# Generated by Django 5.1.5 on 2025-02-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_basic_laws_law_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_lawyer',
            name='Price',
        ),
    ]
