# Generated by Django 5.1.5 on 2025-02-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_book_lawyer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardName', models.CharField(max_length=100)),
                ('CardNumber', models.CharField(max_length=30)),
                ('CardExpiryMonth', models.CharField(max_length=10)),
                ('CardExpiryYear', models.CharField(max_length=4)),
                ('Price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.lawyer_register')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.register')),
            ],
            options={
                'db_table': 'Payment Details',
            },
        ),
    ]
