# Generated by Django 5.1.5 on 2025-02-12 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_payment_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_lawyer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payment_details',
            name='id',
        ),
        migrations.AddField(
            model_name='book_lawyer',
            name='Book_Id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='Book_Id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='App.book_lawyer'),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='Pay_Id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
