# Generated by Django 5.1.5 on 2025-02-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_remove_book_lawyer_id_remove_payment_details_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_lawyer',
            name='Book_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='Pay_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
