# Generated by Django 5.1.5 on 2025-02-12 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_book_lawyer_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='Book_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.book_lawyer'),
        ),
    ]
