# Generated by Django 5.1.5 on 2025-02-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_payment_details_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_laws',
            name='Law_link',
            field=models.CharField(max_length=100),
        ),
    ]
