# Generated by Django 5.1.5 on 2025-02-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_basic_laws_law_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_lawyer',
            name='Book_Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
