# Generated by Django 5.1.5 on 2025-02-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_book_lawyer_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency_Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Emergency Numbers',
            },
        ),
    ]
