# Generated by Django 5.1.5 on 2025-02-14 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_emergency_numbers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emergency_Numbers',
        ),
    ]
