# Generated by Django 5.1.5 on 2025-02-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_delete_emergency_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency_Numbers',
            fields=[
                ('Num_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Emergency Numbers',
            },
        ),
    ]
