# Generated by Django 5.1.5 on 2025-02-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_emergency_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_lawyer',
            name='Book_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lawyer_register',
            name='Image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
