# Generated by Django 5.1.5 on 2025-02-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_book_lawyer_book_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_lawyer',
            name='User_Id',
        ),
    ]
