# Generated by Django 5.1.5 on 2025-02-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_remove_book_lawyer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_lawyer',
            name='Category',
            field=models.CharField(max_length=25),
        ),
    ]
