# Generated by Django 5.1.5 on 2025-02-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_alter_book_lawyer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_lawyer',
            name='Lawyer_Name',
            field=models.CharField(max_length=255),
        ),
    ]
