# Generated by Django 5.1.5 on 2025-02-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_alter_book_lawyer_lawyer_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book_lawyer',
            table='Book_Lawyer',
        ),
    ]
