# Generated by Django 5.1.5 on 2025-02-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_alter_book_lawyer_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_lawyer',
            old_name='Book_Id',
            new_name='Id',
        ),
        migrations.AlterModelTable(
            name='basic_laws',
            table='Basic_Laws',
        ),
        migrations.AlterModelTable(
            name='emergency_numbers',
            table='Emergency_Numbers',
        ),
        migrations.AlterModelTable(
            name='payment_details',
            table='Payment_Details',
        ),
    ]
