# Generated by Django 5.1.5 on 2025-02-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_rename_book_id_book_lawyer_id_alter_basic_laws_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_lawyer',
            old_name='Id',
            new_name='Book_Id',
        ),
    ]
