# Generated by Django 5.1.5 on 2025-02-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_rename_id_book_lawyer_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='case_details',
            name='Case_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
