# Generated by Django 5.1.5 on 2025-02-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_remove_case_details_id_alter_case_details_case_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_details',
            name='User_Id',
        ),
    ]
