# Generated by Django 5.1.5 on 2025-02-21 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_remove_case_details_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_details',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case_details',
            name='Case_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user_details'),
        ),
    ]
