# Generated by Django 5.1.5 on 2025-02-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_case_details_id_alter_case_details_case_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_details',
            name='id',
        ),
        migrations.AddField(
            model_name='case_details',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
