# Generated by Django 5.1.5 on 2025-02-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_remove_case_details_id_case_details_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_details',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='lawyer_register',
            old_name='User_Id',
            new_name='Lawyer_Id',
        ),
    ]
