# Generated by Django 5.1.5 on 2025-02-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_rename_lawyer_id_lawyer_register_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer_register',
            old_name='Id',
            new_name='Lawyer_Id',
        ),
    ]
