# Generated by Django 5.1.5 on 2025-02-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_rename_id_lawyer_register_lawyer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_details',
            name='Case_Id',
        ),
    ]
