# Generated by Django 5.1.5 on 2025-02-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_remove_case_details_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
