# Generated by Django 5.1.5 on 2025-02-24 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_alter_case_details_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_details',
            name='id',
        ),
        migrations.AddField(
            model_name='case_details',
            name='Case_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.user_details'),
        ),
        migrations.AddField(
            model_name='case_details',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
