# Generated by Django 5.1.5 on 2025-02-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_remove_user_details_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_details',
            name='Complaint_Subject',
            field=models.CharField(default='Air Pollution', max_length=255),
        ),
    ]
