# Generated by Django 5.1.5 on 2025-02-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_case_details_complaint_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_details',
            name='Id',
        ),
        migrations.AlterField(
            model_name='case_details',
            name='Case_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
