# Generated by Django 5.1.5 on 2025-02-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_remove_case_details_id_alter_case_details_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_details',
            name='Complaint_Subject',
            field=models.CharField(max_length=255),
        ),
    ]
